# Generated by Django 4.1.2 on 2022-11-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='precio',
        ),
    ]
