# Generated by Django 4.1.2 on 2022-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
