# Generated by Django 4.1.2 on 2022-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_precio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='dia',
            field=models.DateField(default='2005-12-31'),
            preserve_default=False,
        ),
    ]
