# Generated by Django 4.1.2 on 2022-11-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_precio_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productos', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='local',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='precio',
            name='productos',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='blog.productos'),
            preserve_default=False,
        ),
    ]
