# Generated by Django 4.1.2 on 2022-11-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_productos_remove_post_id_alter_post_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.productos'),
        ),
    ]
