# Generated by Django 4.1.2 on 2022-11-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_precio_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.productos'),
            preserve_default=False,
        ),
    ]
