# Generated by Django 4.1.2 on 2022-11-24 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_delete_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('dia', models.DateField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
